@ExpenseTracker.WebAPI_HostAddress = http://localhost:5077

### ======== CREATE EXPENSE ==========

POST {{ExpenseTracker.WebAPI_HostAddress}}/expenses/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "name": "Lunch"
}

### ======== GET EXPENSE BY ID ==========

@ExpenseId2 = 019b8ef4-cfd3-798a-8ba6-59708c5f70c2
GET {{ExpenseTracker.WebAPI_HostAddress}}/expenses/{{ExpenseId2}}
Accept: application/json
Authorization: Bearer {{adminlogin.response.body.$.accessToken}}

### ======== GET ALL EXPENSES OF A USER ==========

GET {{ExpenseTracker.WebAPI_HostAddress}}/expenses/users
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

### ======== SUBMIT AN EXPENSE ==========

@ExpenseId3 = 019b8ef4-cfd3-798a-8ba6-59708c5f70c2
POST {{ExpenseTracker.WebAPI_HostAddress}}/expenses/{{ExpenseId3}}/submit
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "approverId": "9bde275a-0174-4b8e-bf53-fc6d8c166d30"
}

### ========= REJECT AN EXPENSE ==========
@ExpenseId5 = 019b8ef4-cfd3-798a-8ba6-59708c5f70c2
POST {{ExpenseTracker.WebAPI_HostAddress}}/expenses/{{ExpenseId5}}/reject
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "rejectionReason": "Insufficient details provided."
}

### ======== APPROVE AN EXPENSE ==========
@ExpenseId4 = 019b8ef4-cfd3-798a-8ba6-59708c5f70c2
POST {{ExpenseTracker.WebAPI_HostAddress}}/expenses/{{ExpenseId4}}/approve
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

### ======== CREATE RECEIPT ==========

POST {{ExpenseTracker.WebAPI_HostAddress}}/receipts/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "expenseId": "019b8ef4-cfd3-798a-8ba6-59708c5f70c2",
  "amount": 20,
  "date": "2024-06-20T12:00:00Z",
  "receiptNo": "R123456",
  "vendor": "Restaurant"
}

### ======== GET RECEIPTS BY EXPENSE ID ==========
@ExpenseId = 019c14c3-e3f3-788f-933e-379181afecd1
GET {{ExpenseTracker.WebAPI_HostAddress}}/expenses/{{ExpenseId}}/receipts
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

### ========== CREATE USERS ==========

POST {{ExpenseTracker.WebAPI_HostAddress}}/users/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "email": "test1+tt@test.com",
  "password": "P@ssw0rd!"
}

###

POST {{ExpenseTracker.WebAPI_HostAddress}}/users/invite
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "email": "barbaros.yurttagul@gmail.com"
}

### ========== LOGIN USERS ==========

# @name login
POST {{ExpenseTracker.WebAPI_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@ttt.com",
  "password": "Password1!"
}
###

# @name adminlogin
POST {{ExpenseTracker.WebAPI_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "admin@expensetracker.com",
  "password": "Password1!"
}

### ========== CREATE TENANT ===========

POST {{ExpenseTracker.WebAPI_HostAddress}}/tenants
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{adminlogin.response.body.$.token}}

{
  "name": "TT6",
  "code": "TTCode9",
  "description": "Tenant for TT",
  "domain": "tt.com",
  "email": "admin2@tt.com",
  "password": "Password1!"

}

### ========== APPROVER-ROLE ==========

@userId = 401a7471-172b-45f1-a45c-a36260ab1345
POST {{ExpenseTracker.WebAPI_HostAddress}}/users/{{userId}}/roles/approver-role
Accept: application/json
Authorization: Bearer {{adminlogin.response.body.$.accessToken}}

###

@userId = 401a7471-172b-45f1-a45c-a36260ab1345
DELETE {{ExpenseTracker.WebAPI_HostAddress}}/users/{{userId}}/roles/approver-role
Accept: application/json
Authorization: Bearer {{adminlogin.response.body.$.accessToken}}


### ========== BULK USER CREATION ==========

POST {{ExpenseTracker.WebAPI_HostAddress}}/users/bulk
Authorization: Bearer {{login.response.body.$.accessToken}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="CsvFile"; filename="users.csv"
Content-Type: text/csv

Email
aaaaa@test.com
bbbbb@test.com
--boundary--

### ========== LIST USERS ==========
GET {{ExpenseTracker.WebAPI_HostAddress}}/users
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

###
### Get first page of users
# @name getFirstPage
GET {{ExpenseTracker.WebAPI_HostAddress}}/users?pageSize=2
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

### Get next page using cursor from previous response
@nextCursor = {{getFirstPage.response.body.nextCursor}}
GET {{ExpenseTracker.WebAPI_HostAddress}}/users?pageSize=2&cursor={{nextCursor}}
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

### Search first page
# @name searchFirstPage
GET {{ExpenseTracker.WebAPI_HostAddress}}/users?searchQuery=tt&pageSize=2
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

### Search next page - automatically uses cursor from previous response
@searchCursor = {{searchFirstPage.response.body.nextCursor}}
GET {{ExpenseTracker.WebAPI_HostAddress}}/users?searchQuery=tt&pageSize=2&cursor={{searchCursor}}
Accept: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

### ========== UPDATE USER ==========
@userId = 086ca3f6-3136-4c16-8b6c-52211aea4a88
PUT {{ExpenseTracker.WebAPI_HostAddress}}/users/{{userId}}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.accessToken}}

{
  "email": "barb@test.com"
}