@ExpenseTracker.WebAPI_HostAddress = http://localhost:5077

POST {{ExpenseTracker.WebAPI_HostAddress}}/expenses/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "name": "Lunch"
}

###

POST {{ExpenseTracker.WebAPI_HostAddress}}/receipts/
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "expenseId": "0199ab41-b472-7b24-b543-b596286b5ec0",
  "amount": 20,
  "date": "2024-06-20T12:00:00Z",
  "receiptNo": "R123456",
  "vendor": "Restaurant"
}
###
@ExpenseId = 0199ab41-b472-7b24-b543-b596286b5ec0
GET {{ExpenseTracker.WebAPI_HostAddress}}/expenses/{{ExpenseId}}/receipts
Accept: application/json
Authorization: Bearer {{login.response.body.$.token}}

###

POST {{ExpenseTracker.WebAPI_HostAddress}}/users/
Accept: application/json
Content-Type: application/json

{
  "email": "aaa@fff.com",
  "password": "P@ssw0rd!"
}
###

# @name login
POST {{ExpenseTracker.WebAPI_HostAddress}}/users/login
Accept: application/json
Content-Type: application/json

{
  "email": "aaa@fff.com",
  "password": "P@ssw0rd!"
}
###
