@ExpenseTracker.WebAPI_HostAddress = http://localhost:5077

POST {{ExpenseTracker.WebAPI_HostAddress}}/expenses/
Content-Type: application/json
Accept: application/json

{
  "name": "Lunch"
}

###
